deploymentMode: Distributed

ingester:
  replicas: 1
  zoneAwareReplication:
    enabled: false

querier:
  replicas: 1
  maxUnavailable: 1

queryFrontend:
  replicas: 1
  maxUnavailable: 1

queryScheduler:
  replicas: 1

distributor:
  replicas: 1
  maxUnavailable: 1

compactor:
  replicas: 1

indexGateway:
  replicas: 1
  maxUnavailable: 1