# Prometheus Helm values
# Chart: prometheus v27.3.1
# Docs: https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus
#
# These values override the chart defaults.
# Run `helm show values prometheus-community/prometheus` to see all available options.

server:
  service:
    type: ClusterIP

  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093
      scheme: http
      timeout: 10s
      api_version: v2

  extraFlags:
    - web.enable-remote-write-receiver

  persistentVolume:
    enabled: true
    size: 2Gi

  retention: "7d"

serverFiles:
  alerting_rules.yml: #Default filename for alerting rules
    groups:
      - name: weather-api
        rules:
          - alert: WeatherApiDown
            expr: |
              (
                sum(up{job="kubernetes-service-endpoints", kubernetes_namespace="weatherapi", kubernetes_name="weather-api-service"})
                +
                sum(up{job="kubernetes-service-endpoints", namespace="weatherapi", service="weather-api-service"})
              ) < 1
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Weather API is down"
              description: "The weather-api pod has been unreachable for more than 1 minute."
  recording_rules.yml: #Default filename for recording rules
    groups:
      - name: custom-rules
        rules:
          - record: node_memory_MemFree_percent
            expr: 100 - (100 * node_memory_MemFree_bytes / node_memory_MemTotal_bytes)
              
# Alertmanager — disable if not needed
alertmanager:
  enabled: true

# Pushgateway — disable if not needed
prometheus-pushgateway:
  enabled: false


