apiVersion: v1
kind: Service
metadata:
  name: weather-api-service
  namespace: weatherapi
  labels:
    app.kubernetes.io/name: weather-api
    project: weather-api
spec:
  selector:
    app.kubernetes.io/name: weather-api
    project: weather-api
  ports:
    -
      port: 80
      targetPort: 8081
      protocol: TCP
      name: http
  type: ClusterIP
